---
- name: Remove apache2, nginx and passenger
  apt: name={{ item }} state=absent
  with_items:
    - apache2
    - nginx
    - passenger

- name: Install Passenger PGP key
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xAC40B2F7 state=present 

- name: Add HTTPS support for apt
  apt: name={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Find ubuntu distro short name 
  shell: grep $(lsb_release -rs) /usr/share/python-apt/templates/Ubuntu.info | grep -m 1 "Description: Ubuntu " | cut -d "'" -f2 | cut -d ' ' -f1
  register: distro

- name: Add passenger source
  template: src=passenger.list dest=/etc/apt/sources.list.d/passenger.list owner=root group=root mode=0600

- name: Update 
  apt: update_cache=yes

- name: Install packages
  apt: name={{ item }} state=present
  with_items: 
    - nginx-extras
    - passenger
